fname=input("Enter your firstname")
lname=input("Enter your Lastname")
Phone=input("Enter your Phone")
Email=input("Enter yout email")
Address=input("Enter your Address")
Skill1=input("Enter your Skills")
Skill2=input("Enter your Skills")
Degree=input("Enter your Degree")
Stream=input("Enter your Stream")
Cln=input("Enter your College name")
Cyop=input("Enter your College Year of passing")
Clp=input("Enter your College percentage")
Hscs=input("Enter your HSC School name")
Hyop=input("Enter your HSC Year of passing")
Hscp=input("Enter your HSC Perentage")
Sslcs=input("Enter your SSLC School name")
Syop=input("Enter your SSLC Year of passing")
Sslcp=input("Enter your SSLC School percentage")

print("\t \t \t \t \t \t \t \t \t",fname+" "+lname)
print("\t","+91"+Phone,"\t \t \t \t \t \t \t \t \t \t \t \t \t \t \t ","Skills")
print("\t",Email,"\t \t \t \t \t \t \t \t \t \t \t \t \t \t",Skill1)
print("\t",Address,"\t \t \t \t \t \t \t \t \t \t \t \t \t \t \t",Skill2)
print("-------------------------------------------------------------------------------------------------------------------------------------------------------------------")
print("Education")
print("-------------------------------------------------------------------------------------------------------------------------------------------------------------------")
print("\t",Degree+Stream,"\t \t \t \t \t",Cln,"\t \t \t \t \t",Cyop,"\t \t \t \t \t",Clp,"%")
print("\t","HSC","\t \t \t \t \t \t",Hscs,"\t \t \t \t ",Hyop,"\t \t \t \t \t",Hscp,"%")
print("\t","SSLC","\t \t \t \t \t \t",Sslcs,"\t \t \t \t ",Syop,"\t \t \t \t \t",Sslcp,"%")

